CREATE DATABASE IF NOT EXISTS db_nutrition;

USE db_nutrition;

CREATE TABLE IF NOT EXISTS nutritionist (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(35) DEFAULT NULL,
    last_name VARCHAR(30) DEFAULT NULL,
    user VARCHAR(20) DEFAULT NULL,
    email VARCHAR NOT NULL,
    password VARCHAR NOT NULL
); 

CREATE TABLE IF NOT EXISTS patients (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(35) DEFAULT NULL,
    last_name VARCHAR(30) DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS food (
  id_food INT NOT NULL AUTO_INCREMENT,
  name_food VARCHAR(45) NULL,
  description VARCHAR(125) NULL,
  link_photo VARCHAR(125) NULL,
  PRIMARY KEY (id_food) 
);



SELECT
    *
FROM
    nutritionist