CREATE DATABASE IF NOT EXISTS db_nutrition;

USE db_nutrition;

CREATE TABLE IF NOT EXISTS nutritionist (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(35) DEFAULT NULL,
    last_name VARCHAR(30) DEFAULT NULL,
    user VARCHAR(20) DEFAULT NULL,
    email VARCHAR NOT NULL,
    password VARCHAR NOT NULL
)

SELECT * FROM nutritionist